ktor {
    deployment { port = 8080 }
    application { modules = [ com.bigboote.coordinator.ApplicationKt.main ] }
}

bigboote {
    auth {
        provider = ${?BIGBOOTE_AUTH_PROVIDER}
        provider = "stub"
    }
    kurrent {
        connectionString = ${?KURRENTDB_URL}
        connectionString = "esdb://localhost:2113?tls=false"
    }
    db {
        url      = ${?DATABASE_URL}
        url      = "jdbc:postgresql://localhost:5432/bigboote"
        user     = ${?DATABASE_USER}
        user     = "bigboote"
        password = ${?DATABASE_PASSWORD}
        password = "bigboote"
    }
}
